### PR TITLE
Match wp boilerplate master - Support PHP 5.2.x by dropping dir __DIR__

### PR DESCRIPTION
**Pull request by davemac**
To keep in sync with WordPress-Plugin-Boilerplate update

### CODE REVIEW

**Comment by bradvin** [comment]
I wish there was an easy way to keep this in sync with the latest boilerplate code

**Comment by davemac** [comment]
I agree. From what I read here http://tommcfarlin.com/the-state-of-the-wordpress-plugin-boilerplate the bolierplate plugin is going to change dramatically, and grunt could be on the agenda

**Comment by bradvin** [comment]
I am working with Tom on the new version of the boilerplate, and grunt will probably be in there, but not from a grunt-init point of view. The grunt-init templates require very specific tags as you know, eg:

```
{%= title %}
```

And I am pretty sure Tom and the other devs will not want those tags in the code as it will really confuse developers who are starting out and want to use the boilerplate as a jump start.

Perhaps a specific naming convention? I am still unsure

**Comment by davemac** [comment]
Good point. There's an issue here, which is how to cater to beginners but also cater to more advanced developers, too.

Food for thought. As you asked earlier, how do we keep a great plugin like yours (which is for more advanced devs) in sync with the wp boilerplate master?

**Comment by bradvin** [comment]
I was thinking of doing the sync with a grunt build task, so it fetches the latest code from the boilerplate repo, then finds the necessary text in the different files and replaces with our grunt-init tags, then copies the files into the 'root' directory when done.

In theory that should work. I will give it a go when I can

**Comment by davemac** [comment]
Theory sounds good. I suppose with Grunt it can be like fragile scaffolding - if one part breaks then the rest of it falls down. 

Would you build the grunt task to use a git sub module?

**Comment by bradvin** [comment]
I am not sure a git submodule will work with the folder structure of the boilerplate, as grunt-init needs the main plugin files to go directly into

```
https://github.com/fooplugins/grunt-wp-boilerplate/tree/master/root
```

The current boilerplate structure has to copy files from

```
https://github.com/tommcfarlin/WordPress-Plugin-Boilerplate/tree/master/plugin-name
```

And the new structure has an extra 'trunk' folder:

```
https://github.com/tommcfarlin/WordPress-Plugin-Boilerplate/tree/develop/plugin-name/trunk
```

**Pull request merged**
