### PR TITLE
Modify copyright from 2013 to 2014

### PR DESCRIPTION
**Pull request by SweaDev**
Nothing much, just the Copyright year update to 2014.

### CODE REVIEW

**Comment by bradvin** [comment]
@fayazmiraz thanks - I wish there was am easier way to keep the root folder in sync with the boilerplate master branch in some way.

**Comment by SweaDev** [comment]
Yes @bradvin, I was thinking the same this morning.

Only thing that comes to my mind is to make a parser that will rewrite the root folder with the updated version of boilerplate master. Of course, we'll have to update the parser from time to time, but the frequency of having to update the parser will be much less.

I've looked into some boilerplate generators in GitHub, but I like the Grunt approach the most. So I think the best solution would be a combination of parser and grunt.

**Comment by SweaDev** [comment]
On second thought, I think it'll be best for everybody if these two repositories are merged!

I've noticed the [issue consideration](https://github.com/tommcfarlin/WordPress-Plugin-Boilerplate/issues/135) and a [previous discussion](https://github.com/fooplugins/grunt-wp-boilerplate/issues/1).

Of course, best if these two projects are merged, since managing as sub-module may be a pain and unnecessary too.

If these two projects are merged, then only the grunt version will need modification and the place holder plugin may reside in the  `/plugin-name/` directory, which will be basically exported after each modification of the grunt version.

We don't even have to do the export manually if we write a `pre-commit` hook, which will execute the grunt script and add the changes to the `/plugin-name/` directory in commit. Of course, in that case we'll not allow direct changes in the `/plugin-name/` directory.

The benefits of keeping both the grunt version and a place holder `/plugin-name/` version are:
1. People will just be able to copy the `/plugin-name/` directory and use as a new plugin and modify as they like, but they'll not have to use grunt to use the boilerplate.
2. Those who are comfortable with grunt will be able to export without all the hassle of search-and-replace.
3. Also, using default grunt settings, authors will not have to input name/email etc. Too much lazy? :)

One issue in this merge may be preserving the history of both the projects, but I think that can be achieved by doing [something like this](http://scottwb.com/blog/2012/07/14/merge-git-repositories-and-preseve-commit-history/).

I'm just thinking out loud here, what do you think?

**Comment by bradvin** [comment]
@fayazmiraz i love your thinking :) But before we go down that road, these are my thoughts...

I want to look at using a grunt task to pull the latest boilerplate source into the root folder : https://github.com/rubenv/grunt-git#the-gitclone-task

And then perhaps using https://github.com/yoniholmes/grunt-text-replace to replace `plugin-name` with `{%= title %}` etc

This will also mean we have to add an extra install step, so it will end up being something like this:

```
git clone git@github.com:fooplugins/grunt-wp-boilerplate.git %USERPROFILE%/.grunt-init/wp-boilerplate
cd %USERPROFILE%/.grunt-init/wp-boilerplate
grunt
```

thoughts?

**Pull request merged**
